# Generated by Django 6.0.3 on 2026-06-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('judge', 'Judge'), ('scorer', 'Scorer')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional display name, e.g. 'Judge Station 1'.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_access_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
