# Generated by Django 6.0.3 on 2026-05-25 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcategory_judgingevent_criterion_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, help_text='Shown in Match Details → Notes row'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_label',
            field=models.CharField(choices=[('group_stage', 'Group Stage'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('other', 'Other')], default='group_stage', help_text='Stage of the competition shown as a badge', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_full',
            field=models.CharField(blank=True, help_text="Full venue address, e.g. 'USTP Oroquieta Campus'", max_length=300),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Short team bio shown on the Team Details page'),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show this match in the 'UP NEXT' featured slot"),
        ),
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(default='#00C5D9', help_text='Hex color code, e.g. #FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_icon',
            field=models.CharField(blank=True, help_text="Short abbreviation shown inside the hexagon logo, e.g. 'IT'", max_length=50),
        ),
    ]
