# Generated by Django 5.2.14 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Model field length update only.

    The live portal `events_team` table uses a different schema (image/members/code)
    and does not have `logo_icon`, so this migration updates Django state without
    altering the portal database.
    """

    dependencies = [
        ("events", "0007_judgescore_approval_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="team",
                    name="logo_icon",
                    field=models.CharField(
                        blank=True,
                        help_text="Emoji, short code, or image URL for the team logo",
                        max_length=500,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
